CREATE DATABASE IF NOT EXISTS Albums;

USE Albums;
CREATE TABLE Artist(
	ARTIST_ID INT PRIMARY KEY AUTO_INCREMENT,
  NAME VARCHAR(30) NOT NULL
) ENGINE = InnoDB;

CREATE TABLE Genre(
GENRE_ID INT PRIMARY KEY AUTO_INCREMENT,
NAME VARCHAR(20) NOT NULL
) ENGINE = InnoDB;

CREATE TABLE Album(
ALBUM_ID INT PRIMARY KEY AUTO_INCREMENT,
ARTIST_ID INT NOT NULL,
TITLE VARCHAR(50) NOT NULL,
PRICE DOUBLE NOT NULL,
GENRE_ID INT NOT NULL,
FOREIGN KEY (ARTIST_ID) REFERENCES Artist(ARTIST_ID),
FOREIGN KEY (GENRE_ID) REFERENCES Genre(GENRE_ID)
) ENGINE = InnoDB;

CREATE TABLE Song(
	SONG_ID INT PRIMARY KEY AUTO_INCREMENT,
  NAME VARCHAR(50) NOT NULL,
  ALBUM_ID INT NOT NULL,
  FOREIGN KEY (ALBUM_ID) REFERENCES Album(ALBUM_ID)
) ENGINE = InnoDB;
