const OK_STATUS = 200;
const CREATED_STATUS = 201;
const NOT_FOUND = 404;
const UNPROCESSABLE_ENTITY_STATUS = 422;

module.exports = {
  OK_STATUS,
  CREATED_STATUS,
  NOT_FOUND,
  UNPROCESSABLE_ENTITY_STATUS
};
